# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
      - name: Package project into executables
        run: npx pkg . --compress brotli

      - name: Upload Linux Build Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/video-sync-linux
          asset_name: video-sync_linux_x64
          tag: ${{ github.ref }}
          overwrite: true
          # body: "This is my release text"
      - name: Upload Windows Build Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/video-sync-win.exe
          asset_name: video-sync_windows_x64.exe
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload MacOS Build Artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/video-sync-macos
          asset_name: video-sync_macos
          tag: ${{ github.ref }}
          overwrite: true
